#################################################################################
# Tractus-X - Digital Product Pass Application
#
# Copyright (c) 2022, 2024 BMW AG
# Copyright (c) 2022, 2024 Henkel AG & Co. KGaA
# Copyright (c) 2023, 2024 CGI Deutschland B.V. & Co. KG
# Copyright (c) 2023, 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################


spring:
  name: 'Catena-X Digital Product Passport Consumer Backend'
  main:
    allow-bean-definition-overriding: true
  devtools:
    add-properties: false
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    utils: INFO

configuration:
  maxRetries: 5

  keycloak:
    realm: CX-Central
    resource: Cl13-CX-Battery
    tokenUri: 'https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token'
    userInfoUri: 'https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/userinfo'

  edc:
    endpoint: 'https://materialpass.int.demo.catena-x.net/consumer'
    readiness: '/api/check/readiness'
    management: '/management/v2'
    catalog: '/catalog/request'
    negotiation: '/contractnegotiations'
    transfer: '/transferprocesses'
    receiverEndpoint: 'https://dpp.int.demo.catena-x.net/endpoint'
    delay:  100 # -- Negotiation status Delay in milliseconds in between async requests [<= 500]
    transferType: "HttpData-PULL"
    timeout:
      exchange: 10
    authorizationKey: "Authorization"

  security:
    authorization:
      bpnAuth: false
      roleAuth: false
    startUpChecks:
      bpnCheck: false
      edcCheck: false
    authentication:
      header: "X-Api-Key"

  irs:
    enabled: true
    endpoint: "https://materialpass-irs.int.demo.catena-x.net"
    paths:
      job: "/irs/jobs"
    tree:
      fileName: "treeDataModel"
      indent: true
    callbackUrl: "https://materialpass.int.demo.catena-x.net/api/irs"

  dtr:
    assetPropType: 'asset:prop:type'
    assetType: 'data.core.digitalTwinRegistry'
    endpointInterface: 'SUBMODEL-3.0'
    dspEndpointKey: 'dspEndpoint'
    semanticIdTypeKey: 'Submodel'
    policyCheck:
      enabled: true
      strictMode: false # The strict mode is quicker and requires less computation complexity, the default mode is comparing against every single object value
      # List of allowed permissions policies
      policies:
        - permission:
            - action: "odrl:use"
              logicalConstraint: "odrl:and"
              constraints:
                - leftOperand: "cx-policy:Membership"
                  operator: "odrl:eq"
                  rightOperand: "active"
                - leftOperand: "cx-policy:UsagePurpose"
                  operator: "odrl:eq"
                  rightOperand: "cx.core.digitalTwinRegistry:1"
          prohibition: []
          obligation: []

    decentralApis:
      search: "/lookup/shells"
      digitalTwin: "/shell-descriptors"
      subModel: "/submodel-descriptors"
    timeouts:
      search: 10
      negotiation: 10
      dtrRequestProcess: 40
      transfer: 10
      digitalTwin: 20
    temporaryStorage:
      enabled: true
      lifetime: 12 # -- Hours

  discovery:
    endpoint: "https://semantics.int.demo.catena-x.net/discoveryfinder/api/v1.0/administration/connectors/discovery/search"
    bpn:
      key: "manufacturerPartId"
      searchPath: "/api/v1.0/administration/connectors/bpnDiscovery/search"
      timeout: 1500
    edc:
      key: "bpn"
      timeout: 1500

  single-api:
    maxRetries: 30
    delay: 1000

  process:
    store: true
    dir: 'process'
    indent: true
    signKey: 'c55e3f35200f6afedbce37cefdaf40eadd15c92814edfdbc4d6ab0eacdcdd56dbcd5a2a34ca4b675084d33f9f479d7d79347795148aaf4443e1b47ab96b27e72'

  passport:
    defaultIdType: "partInstanceId"
    searchIdSchema: "CX:<manufacturerPartId>:<partInstanceId>"
    dataTransfer:
      encrypt: true
      indent: true
      dir: "data/transfer"
    aspects:
      - "urn:samm:io.catenax.battery.battery_pass:6.0.0#BatteryPass"
      - "urn:samm:io.catenax.transmission.transmission_pass:3.0.0#TransmissionPass"
      - "urn:samm:io.catenax.generic.digital_product_passport:5.0.0#DigitalProductPassport"
    policyCheck:
      enabled: true
      strictMode: false
      policies:
        - permission:
            - action: "odrl:use"
              logicalConstraint: "odrl:and"
              constraints:
                - leftOperand: "cx-policy:Membership"
                  operator: "odrl:eq"
                  rightOperand: "active"
                - leftOperand: "cx-policy:FrameworkAgreement"
                  operator: "odrl:eq"
                  rightOperand: "CircularEconomy:1.0"
                - leftOperand: "cx-policy:UsagePurpose"
                  operator: "odrl:eq"
                  rightOperand: "cx.circular.dpp:1"
          prohibition: [ ]
          obligation: [ ]

  verification:
    enabled: true
    autoVerify: true
    wallet:
      url: "https://dpp-consumer-wallet.int.demo.catena-x.net"
      endpoints:
        health: "/health"
        verify: "/verify"
    certifiedDataCredential:
      ## -- These keys are used in order to find if a subModel contains a verifiable credential
      semanticIdKeys:
        - key: "Entity"
          value: "https://www.w3.org/ns/credentials/v2"
        - key: "DataElement"
          value: "urn:samm:io.catenax.dpp_verification.cdc:1.0.0#CertifiedDataCredential"
        - key: "Operation"
          value: "https://w3c.github.io/vc-jws-2020/contexts/v1/"

  vault:
    type: 'local'
    file: 'vault.token.yml'
    pathSep: "."
    prettyPrint: true
    indent: 2
    defaultValue: '<Add secret value here>'
    attributes:
      - "appId"
      - "client.id"
      - "client.secret"
      - "edc.apiKey"
      - "edc.participantId"
      - "oauth.apiKey"
      - "irs.apiKey"
      - "wallet.apiKey"

server:
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ON_PARAM
    include-exception: false
  port: 8888
  tomcat:
    max-connections: 10000
