#################################################################################
# Tractus-X - Digital Product Pass Application 
#
# Copyright (c) 2022, 2024 BMW AG
# Copyright (c) 2022, 2024 Henkel AG & Co. KGaA
# Copyright (c) 2023, 2024 CGI Deutschland B.V. & Co. KG
# Copyright (c) 2023, 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

backend:
  image:
    pullPolicy: Always
  ingress:
    enabled: true
    className: ""
    annotations:
      # ingressClassName: nginx
      # kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: addon-http-application-routing
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: &hostname  "localhost"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tls-secret-digital-product-pass-backend
        hosts:
          - *hostname
  edc:
    xApiKey: "<EDC_API_KEY>"
    participantId: &bpn <BPN_NUMBER>
    hostname: "<CONSUMER_EDC_CONTROPLANE_URL>"


  hostname: *hostname
  securityCheck:
    bpn: true
    edc: true

  irs:
    enabled: false
    hostname: "<DPP_IRS_URL>"
    apiKey: <IRS_API_KEY>

  process:
    encryptionKey: "<SIGN_KEY>"

  discovery:
    hostname: "<SENAMTICS_URL>/discoveryfinder"

  singleApi:
    maxRetries: 30
    delay: 1000

  verification:
    wallet:
      url: "<CONSUMER_WALLET_URL>"
      apiKey: "<API_KEY>"

frontend:
  enabled: true
  image:
    pullPolicy: Always
  ingress:
    enabled: true
    className: ""
    annotations:
      # ingressClassName: nginx
      # kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: addon-http-application-routing
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: &hostname  "localhost"
        paths:
          - path: /passport(/|$)(.*)
            pathType: Prefix
    tls:
      - secretName: tls-secret-digital-product-pass-frontend
        hosts:
          - *hostname

  backend:
    hostname: *hostname

  supportContact:
    adminEmail: "admin@example.com"

  portal:
    hostname: "<PORTAL_URL>"


oauth:
  hostname: "<CENTRAL_IDP_URL>"
  techUser:
    clientId: <CLIENT_ID>
    clientSecret: <CLIENT_SECRET>
  realm: <REALM>
  appId: <APP_ID>
  bpnCheck:
    enabled: false
    bpn: *bpn
  roleCheck:
    enabled: false
  apiKey:
    header: "X-Api-Key"
    secret: <API_KEY>

